---
# Обработчики для роли security

- name: restart ssh
  service:
    name: "{{ ssh_service_name }}"
    state: restarted

- name: restart fail2ban
  service:
    name: "{{ fail2ban_service_name | default('fail2ban') }}"
    state: restarted
  ignore_errors: yes
  when: fail2ban_service_name is defined or fail2ban_installed.rc == 0

- name: reload ufw
  command: ufw reload
  when: enable_firewall | bool

- name: reload unattended-upgrades
  service:
    name: unattended-upgrades
    state: restarted
  ignore_errors: yes
