FROM docker.io/n8nio/n8n:1.90.2

WORKDIR /home/node

# Копируем package.json и устанавливаем зависимости
COPY package.json .
RUN npm install

# Возвращаемся в рабочую директорию n8n
WORKDIR /home/node/.n8n
