server:
  host: 0.0.0.0
  port: 8000
  cors:
    allowed_origins:
      - "*"
    allow_credentials: true

datastore:
  type: postgres
  postgres:
    dsn: "postgres://zep:zep@postgres-zep:5432/zep?sslmode=disable"

nlp:
  tokenizer: local
  embedder:
    service: "http://embeddings-service:8080"
    type: "huggingface"
    dimensions: 384  # для all-MiniLM-L6-v2
  chunker:
    strategy: recursive
    parameters:
      chunk_size: 256            # Оптимизированный размер
      chunk_overlap: 25          # Небольшое перекрытие для связности
      separators:
        - "\n\n"                 # Параграфы
        - "\n"                   # Строки
        - ". "                   # Предложения
        - "! "                   # Восклицания
        - "? "                   # Вопросы
        - ":"                    # Перечисления
        - ";"                    # Перечисления
        - ","                    # Списки
        - " "                    # Слова (последний вариант)

memory:
  message_window: 15             # Увеличенное окно сообщений
  auto_summarize: true           # Включаем автоматическое резюмирование
  auto_summarize_threshold: 12   # Порог для автоматического резюмирования
