---
# Роль n8n-setup - основные задачи

- name: Создание директории проекта
  file:
    path: "{{ project_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0755'
  tags: n8n-setup

- name: Клонирование репозитория проекта
  git:
    repo: "{{ git_repo }}"
    dest: "{{ project_dir }}"
    version: "{{ git_branch }}"
    force: yes
  become_user: "{{ ansible_user }}"
  tags: n8n-setup

- name: Создание необходимых директорий
  file:
    path: "{{ project_dir }}/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "logs/n8n"
    - "logs/zep"
    - "logs/postgres"
    - "logs/postgres-zep"
    - "logs/nginx"
    - "logs/redis"
    - "logs/weaviate"
    - "nginx/certs"
    - "backups"
  tags: n8n-setup

- name: Создание .env файла
  template:
    src: env.j2
    dest: "{{ project_dir }}/.env"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: '0600'
  tags: n8n-setup

- name: Создание SSL сертификатов, если они еще не существуют
  shell: |
    if [ ! -f {{ project_dir }}/nginx/certs/server.crt ]; then
      openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
        -keyout {{ project_dir }}/nginx/certs/server.key \
        -out {{ project_dir }}/nginx/certs/server.crt \
        -subj "/C=RU/ST=State/L=City/O=Organization/CN=localhost"
    fi
  args:
    executable: /bin/bash
    creates: "{{ project_dir }}/nginx/certs/server.crt"
  tags: n8n-setup

- name: Установка прав выполнения для скриптов
  file:
    path: "{{ project_dir }}/{{ item }}"
    mode: '0755'
  loop:
    - "setup.sh"
    - "rotate-logs.sh"
    - "check-system.sh"
    - "fix-issues.sh"
    - "import-templates.sh"
    - "make-scripts-executable.sh"
  tags: n8n-setup

# Проверка версии Docker для определения формата команд docker-compose
- name: Проверка версии Docker
  command: docker --version
  register: docker_version
  changed_when: false
  failed_when: false
  tags: n8n-setup

- name: Проверка наличия docker-compose
  command: which docker-compose
  register: docker_compose_check
  changed_when: false
  failed_when: false
  tags: n8n-setup

- name: Проверка наличия docker compose plugin
  command: docker compose version
  register: docker_compose_plugin
  changed_when: false
  failed_when: false
  tags: n8n-setup

- name: Определение формата команды docker-compose
  set_fact:
    docker_compose_cmd: "{{ 'docker-compose' if docker_compose_check.rc == 0 else 'docker compose' }}"
  tags: n8n-setup

- name: Проверка уже установленных контейнеров
  shell: "{{ docker_compose_cmd }} ls 2>/dev/null || docker ps -a --format '{{.Names}}' | grep -q n8n"
  register: docker_check
  failed_when: false
  changed_when: false
  tags: n8n-setup

- name: Проверка наличия файла .n8n_api_key
  stat:
    path: "{{ project_dir }}/.n8n_api_key"
  register: api_key_file
  tags: n8n-setup

# Обновление Makefile для поддержки разных версий Docker Compose
- name: Проверка и обновление Makefile (если используется)
  block:
    - name: Проверка наличия Makefile
      stat:
        path: "{{ project_dir }}/Makefile"
      register: makefile_check
      tags: n8n-setup

    - name: Чтение содержимого Makefile
      slurp:
        src: "{{ project_dir }}/Makefile"
      register: makefile_content
      when: makefile_check.stat.exists
      tags: n8n-setup

    - name: Обновление Makefile для поддержки обеих версий docker-compose
      replace:
        path: "{{ project_dir }}/Makefile"
        regexp: 'docker-compose'
        replace: "{{ docker_compose_cmd }}"
      when: 
        - makefile_check.stat.exists
        - docker_compose_cmd == "docker compose"
        - "'docker-compose' in (makefile_content.content | b64decode)"
      tags: n8n-setup
  when: makefile_check is defined and makefile_check.stat is defined
  ignore_errors: yes

# Создание простого запускающего скрипта, если make недоступен
- name: Создание простого скрипта запуска docker-compose
  copy:
    dest: "{{ project_dir }}/run-compose.sh"
    content: |
      #!/bin/bash
      cd "$(dirname "$0")"
      {{ docker_compose_cmd }} up -d
    mode: '0755'
  tags: n8n-setup

- name: Запуск проекта через make setup или docker-compose напрямую
  block:
    - name: Запуск через make setup (если доступен)
      command: make setup
      args:
        chdir: "{{ project_dir }}"
      become_user: "{{ ansible_user }}"
      register: setup_result
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
      when: makefile_check.stat.exists
      failed_when: false

    - name: Запуск напрямую через docker-compose (если make fail)
      shell: "{{ docker_compose_cmd }} up -d"
      args:
        chdir: "{{ project_dir }}"
      become_user: "{{ ansible_user }}"
      when: 
        - setup_result is defined and setup_result.rc != 0
        - not makefile_check.stat.exists
  when: docker_check.rc != 0 or not api_key_file.stat.exists
  retries: 2
  delay: 30
  tags: n8n-setup

- name: Проверка запущенных контейнеров
  command: docker ps
  register: docker_status
  changed_when: false
  tags: n8n-setup

- name: Вывод информации о запущенных контейнерах
  debug:
    var: docker_status.stdout_lines
  tags: n8n-setup

- name: Проверка работоспособности системы
  command: "{{ project_dir }}/check-system.sh"
  become_user: "{{ ansible_user }}"
  register: check_result
  ignore_errors: yes
  tags: n8n-setup

- name: Вывод результатов проверки системы
  debug:
    var: check_result.stdout_lines
  when: check_result is not failed
  tags: n8n-setup

- name: Настройка ротации логов
  cron:
    name: "Ротация логов n8n-super-agent"
    user: "{{ ansible_user }}"
    job: "cd {{ project_dir }} && ./rotate-logs.sh > /dev/null 2>&1"
    hour: "2"
    minute: "0"
  when: enable_backups
  tags: n8n-setup, maintenance

- name: Настройка резервного копирования
  cron:
    name: "Резервное копирование n8n-super-agent"
    user: "{{ ansible_user }}"
    job: "cd {{ project_dir }} && make backup > /dev/null 2>&1"
    cron_file: n8n-super-agent-backup
    hour: "3"
    minute: "0"
  when: enable_backups
  tags: n8n-setup, maintenance

- name: Настройка очистки старых резервных копий
  cron:
    name: "Очистка старых резервных копий n8n-super-agent"
    user: "{{ ansible_user }}"
    job: "find {{ backup_dir }} -type f -name '*.sql' -mtime +{{ backup_retention_days }} -delete; find {{ backup_dir }} -type f -name '*.tar.gz' -mtime +{{ backup_retention_days }} -delete"
    cron_file: n8n-super-agent-backup-cleanup
    hour: "4"
    minute: "0"
  when: enable_backups
  tags: n8n-setup, maintenance