---
# Роль Docker - основные задачи

- name: Проверка наличия Docker
  command: docker --version
  register: docker_version_check
  failed_when: false
  changed_when: false
  tags: docker

- name: Добавление ключа GPG Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: docker_version_check.rc != 0
  tags: docker

- name: Добавление репозитория Docker
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  tags: docker

- name: Установка Docker и Docker Compose
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  notify: restart docker
  tags: docker

- name: Настройка параметров Docker daemon
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "log-driver": "json-file",
        "log-opts": {
          "max-size": "100m",
          "max-file": "3"
        },
        "default-address-pools": [
          {"base": "172.17.0.0/16", "size": 24}
        ]
      }
    mode: '0644'
    owner: root
    group: root
  notify: reload docker
  tags: docker

- name: Включение и запуск службы Docker
  service:
    name: docker
    state: started
    enabled: yes
  tags: docker

- name: Установка docker-compose через pip
  pip:
    name: docker-compose
    state: present
  tags: docker

- name: Создание группы docker
  group:
    name: docker
    state: present
  tags: docker

- name: Добавление пользователя в группу docker
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  tags: docker

- name: Применение изменений группы docker (перезагрузка только если необходимо)
  meta: reset_connection
  tags: docker